services:
  backend:
    ports:
      - "127.0.0.1:8082:8080"
    environment:
      SPRING_PROFILES_ACTIVE: prod
      FRONTEND_URL: "http://1inf54-983-6f.inf.pucp.edu.pe"
      JAVA_OPTS: "-Xmx512m -Xms256m"

  frontend:
    image: ghcr.io/kevindm17/aeroluggage-frontend:latest
    build:
      args:
        BACKEND_API_BASE_URL: /api
        BACKEND_WS_BASE_URL: ""
    ports:
      - "127.0.0.1:3000:80"
