services:
  backend:
    ports:
      - "127.0.0.1:8082:8080"
    environment:
      SPRING_PROFILES_ACTIVE: prod
      FRONTEND_URL: "http://1inf54-983-6f.inf.pucp.edu.pe"

  frontend:
    build:
      args:
        BACKEND_API_BASE_URL: ""
        BACKEND_WS_BASE_URL: ""
    ports:
      - "127.0.0.1:3000:80"
