spring.application.name=aero-luggage

spring.datasource.url=jdbc:sqlite:aeroluggage.db
spring.datasource.driver-class-name=org.sqlite.JDBC

spring.sql.init.mode=always

#Comentar en produccion
spring.profiles.active=dev
